Mount Google Drive to Session

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Setup kaggle

In [ ]:
import os
os.environ['KAGGLE_CONFIG_DIR'] = "/content/drive/My Drive/kaggle"

Download a dataset

In [ ]:
%cd /content/drive/My Drive/colab_data/datasets
#os.mkdir('titanic_dataset')
%cd titanic_dataset

In [ ]:
#!kaggle competitions download -c titanic
!ls

Load Dataset and Apply ML algorithms

In [ ]:
import pandas as pd
df = pd.read_csv("train.csv")
print(df.info())
df.head()

In [ ]:
df["Surname"] = df["Name"].str.split(",").str.get(0)
df["FirstName"] = df["Name"].str.split(",").str.get(1)
df = df.drop(columns='Name')
df.head()